### ISSUE TITLE
Alternative Didactic Model

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-self-learning#29] opened 2023-02-09 07:43 UTC
Nano-Modules should support an alternative didactic model. When enables the Nano-Moduls should be presented as follows:

1. Present a question to activate knowledge (Vorwissensaktivierung). This should be an open question, which is not evaluated. For instance: "Was wissen Sie bereits zu dem Thema XYZ".
2. Present the content.
3. Present open question where students may justify their answers/thoughts that are questioned in the last question. Also these answers are not evaluated. For instance:
   - "A ist ein (un-)gültiges Konzept, weil..."
   - "B ist ein (un-)gültiges Konzept, weil..."
   - "C ist ein (un-)gültiges Konzept, weil..."
4. Present the questionnaire (typically a multiple choice question) that is evaluated. For instance: "Wählen Sie die gültigen Konzepte aus: A. B, C"

Optionally, teachers may annotate the question with a slider regarding the student's confidence of the answer.

To support this feature, we need to extend Nano-Modules as follows:
- [x] We need to store additional open questions, which are not evaluated. For 1, & 3
- [ ] Teachers must be able to choose among the current form and the alternative didactic model
- [ ] The learning view must switch to the alternative presentation mode when presenting such a Nano-Module (steps 1, 2, 3, and 4).
- [ ] Evaluation of only the last question
- [ ] Support for the confidence sliders (already implemented, but not sure how answers should be handled by the platform).

**Comment by spark-sse** [comment] 2023-05-02 17:49
Duplicate of #8 ?

**Comment by spark-sse** [comment] 2023-05-02 17:52
@Arne1303 this issue has a more profound explanation with checkmarks. 

Maybe its smart that you read this as well and fill out the checks. I won't close it as duplicate and close it alongside the issue #8 instead (when it is solved).

**Closed** 2023-06-28 09:05 UTC
Labels: Feature
