### ISSUE TITLE
User Statistics

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-self-learning#39] opened 2023-04-17 12:06 UTC
Provide possibility (data) to collect data about registered users / usage. The motivation behind is to collect monthly reports how many users are registered at the self learn platform and to provide optionally the possibility to subtract users that do not use the platform anymore. For this we should collect the following data (check if this is not already provided by the Account table):
- No. of distinct users
- Time when they have been registered for the first time
- Time when they have been signed last time

Further provide an API to export this data: Either run it as part of the web side (probably not supported by the React framework) or run a separate service that calls the API at a specified time and dumps the requested data in a CSV file (or a separate DB).

Tasks:
- [ ] Adapt/Check data model
- [ ] Write export API
- [ ] Write export service

**Comment by spark-sse** [comment] 2023-06-28 09:21
duplicate of #46

**Closed by spark-sse** 2023-06-28 09:21 UTC
Labels: type: feature
